kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: bff-vs
  namespace: bff
spec:
  hosts:
    - '*'
  gateways:
    - bff-gw
  http:
    - match:
        - uri:
            prefix: /cnhsit
      route:
        - destination:
            host: cnhsit
            port:
              number: 8080
            subset: version-v1
          weight: 50
        - destination:
            host: cnhsit
            port:
              number: 8080
            subset: version-v2
          weight: 50
    - match:
        - uri:
            prefix: /cdhusts
      route:
        - destination:
            host: cdhusts
            port:
              number: 8080