-- Script Database

CREATE TABLE CNH_SIT (
CPF VARCHAR(11),
CNH_NRO VARCHAR(50),
CNH_STATUS VARCHAR(50)
--O    VENCIDA
--O    CASSADA
--O    ATIVA
)

SELECT * FROM CNH_SIT
INSERT INTO DBO.CNH_SIT values ('11111111111','00001230000','CASSADA')
DELETE FROM CNH_SIT 

CREATE TABLE CNH_REN  (
 
CPF VARCHAR(11),
NOME VARCHAR(255),
CNH_NRO VARCHAR(50),
REN_SITUACAO VARCHAR(50),
--•    AGENDADO
--•    NÃO AGENDADO
REN_DATA DATE,
REN_PROTOCOLO VARCHAR(50),
REN_STATUSSERVICO VARCHAR(50),
--O    OK
--O    OFF
REN_STATUS VARCHAR(50),
--O    SOLICITAÇÃO
--O    EXAME MEDICO
--O    PAGAMENTO DE TAXA
--O    EMISSAO DE CNH
--O    ENVIO DE CNH
REN_BOLETOPAGAMENTO VARCHAR(255))
 
 
CREATE TABLE CDHU_DOCSTATUS (
CPF VARCHAR(11),
CDHU_NROCONTA VARCHAR(50),
CDHU_STATUS VARCHAR(50))

CREATE TABLE person (
    id INTEGER IDENTITY(1,1) PRIMARY KEY, 
    name VARCHAR(64)
)

INSERT INTO person(name) 
VALUES('Camara'), ('Lucas')