kind: Service
apiVersion: v1
metadata:
  name: cnhstsproc
  labels:
    app: cnhstsproc
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: cnhstsproc
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: cnhstsproc
  labels:
    app: cnhstsproc
    app.kubernetes.io/component: cnhstsproc
    app.kubernetes.io/instance: cnhstsproc
    app.kubernetes.io/name: cnhstsproc
    app.kubernetes.io/part-of: cnhstsproc
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 14-ubi7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnhstsproc
  template:
    metadata:
      labels:
        app: cnhstsproc
        deploymentconfig: cnhstsproc
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: cnhstsproc
          image: "$IMAGE"
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: DATABASE_USER
              value: "$DATABASE_USER"
            - name: DATABASE_PWS
              value: "$DATABASE_PWS"
            - name: SERVER_NAME
              value: "$SERVER_NAME"
            - name: DATABASE_NAME
              value: "$DATABASE_NAME"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
      imagePullSecrets:
        - name: acr-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

