# This example workflow will build container image
# of the application using source to image build
# startegy and push the image to ghcr.io (Image registry)

name: cnhsit
on: 
  push:
    branches:
      - new
    paths:
      - "cnhsit/**"
env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.token }}
  APP_NAME: cnhsit
  IMAGE_TAGS: latest ${{ github.sha }}
  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: "testelucas"
  
  DATABASE_PWS: ${{ secrets.DATABASE_PWS }}
  DATABASE_USER: ${{ secrets.DATABASE_USER }}
  SERVER_NAME: ${{ secrets.SERVER_NAME }}
  DATABASE_NAME: ${{ secrets.DATABASE_NAME }}

jobs:
  deploy:
    uses: lucas2179/api-nodejs-mysql/.github/workflows/teste.yml@new
    with:
      app_name: cnhsit
      image_registry: ghcr.io/${{ github.repository_owner }}
      image_tags: latest ${{ github.sha }}
    secrets:
      registry_password: ${{ secrets.token }}
      openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
      openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
      openshift_namespace: "testelucas"
      database_pws: ${{ secrets.DATABASE_PWS }}
      database_name: ${{secrets.DATABASE_NAME}}
      database_user: ${{secrets.DATABASE_USER}}
      server_name: ${{secrets.SERVER_NAME}}
      registry_user: ${{ github.actor }}

